default_stages: [push]
fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.6
    hooks:
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
  - repo: https://github.com/fpgmaas/deptry.git
    rev: 0.23.0
    hooks:
      - id: deptry
        files: ^(src|tests)/